name: test

on: [ push, pull_request ]

jobs:
  run:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
    name: ClickHouse Utility Bash script tests

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup ClickHouse server
        uses: EpicStep/clickhouse-github-action@v1.0.0

      - name: Install ClickHouse client
        run: sudo apt-get update && sudo apt-get install apt-transport-https ca-certificates dirmngr && sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E0C56BD4 && echo "deb https://repo.clickhouse.com/deb/stable/ main/" | sudo tee /etc/apt/sources.list.d/clickhouse.list && sudo apt-get update && sudo apt-get install -y clickhouse-client

      - name: Test ClickHouse server with client
        run:  clickhouse-client --host="127.0.0.1" --port=9000 --query="select version()"

      - name: shunit setup
        run: cd tests/ && git clone https://github.com/kward/shunit2

      - name: Run shunit test suites
        run: cd tests/ && ./run_tests.sh
